/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AnthropicApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DeepgramAccessToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ExaApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MyBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MyFunction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "ProcessingJobs": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "WorkerFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}